name: handbook-compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Typst
      run: cargo install typst-cli

    - name: Compile Handbook
      run: typst compile main.typ

    - name: Upload compiled document
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: main.pdf
