name: compile-pdf

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

  install_compile_deploy:

    runs-on: ubuntu-latest

    needs: setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Typst, Compile Document, and Deploy
      run: |
        sudo apt update
        sudo apt install -y cargo
        cargo install typst-cli
        typst compile main.typ
        ls -al # List files to check if main.pdf exists
        if [ -f "main.pdf" ]; then
          mkdir -p public
          cp main.pdf public/
          cd public
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy PDF to GitHub Pages"
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
        else
          echo "main.pdf not found, skipping deployment."
        fi
    
    - name: Upload compiled document
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: main.pdf
